<?php

/* custom routes generated by CRUD */



Route::group(array('prefix' => '', 'as'=>''), function () {

Route::get('pegawais', ['as'=> 'pegawais.index', 'uses' => 'PegawaiController@index']);
Route::post('pegawais', ['as'=> 'pegawais.store', 'uses' => 'PegawaiController@store']);
Route::get('pegawais/create', ['as'=> 'pegawais.create', 'uses' => 'PegawaiController@create']);
Route::put('pegawais/{pegawais}', ['as'=> 'pegawais.update', 'uses' => 'PegawaiController@update']);
Route::patch('pegawais/{pegawais}', ['as'=> 'pegawais.update', 'uses' => 'PegawaiController@update']);
Route::get('pegawais/{id}/delete', array('as' => 'pegawais.delete', 'uses' => 'PegawaiController@getDelete'));
Route::get('pegawais/{id}/confirm-delete', array('as' => 'pegawais.confirm-delete', 'uses' => 'PegawaiController@getModalDelete'));
Route::get('pegawais/{pegawais}', ['as'=> 'pegawais.show', 'uses' => 'PegawaiController@show']);
Route::get('pegawais/{pegawais}/edit', ['as'=> 'pegawais.edit', 'uses' => 'PegawaiController@edit']);

});



Route::group(array('prefix' => '', 'as'=>''), function () {

Route::get('perangkats', ['as'=> 'perangkats.index', 'uses' => 'PerangkatController@index']);
Route::post('perangkats', ['as'=> 'perangkats.store', 'uses' => 'PerangkatController@store']);
Route::get('perangkats/create', ['as'=> 'perangkats.create', 'uses' => 'PerangkatController@create']);
Route::put('perangkats/{perangkats}', ['as'=> 'perangkats.update', 'uses' => 'PerangkatController@update']);
Route::patch('perangkats/{perangkats}', ['as'=> 'perangkats.update', 'uses' => 'PerangkatController@update']);
Route::get('perangkats/{id}/delete', array('as' => 'perangkats.delete', 'uses' => 'PerangkatController@getDelete'));
Route::get('perangkats/{id}/confirm-delete', array('as' => 'perangkats.confirm-delete', 'uses' => 'PerangkatController@getModalDelete'));
Route::get('perangkats/{perangkats}', ['as'=> 'perangkats.show', 'uses' => 'PerangkatController@show']);
Route::get('perangkats/{perangkats}/edit', ['as'=> 'perangkats.edit', 'uses' => 'PerangkatController@edit']);

});



Route::group(array('prefix' => '', 'as'=>''), function () {

Route::get('peminjaman', ['as'=> 'peminjaman.index', 'uses' => 'PeminjamanController@index']);
Route::post('peminjaman', ['as'=> 'peminjaman.store', 'uses' => 'PeminjamanController@store']);
Route::get('peminjaman/create', ['as'=> 'peminjaman.create', 'uses' => 'PeminjamanController@create']);
Route::put('peminjaman/{peminjaman}', ['as'=> 'peminjaman.update', 'uses' => 'PeminjamanController@update']);
Route::patch('peminjaman/{peminjaman}', ['as'=> 'peminjaman.update', 'uses' => 'PeminjamanController@update']);
Route::get('peminjaman/{id}/delete', array('as' => 'peminjaman.delete', 'uses' => 'PeminjamanController@getDelete'));
Route::get('peminjaman/{id}/confirm-delete', array('as' => 'peminjaman.confirm-delete', 'uses' => 'PeminjamanController@getModalDelete'));
Route::get('peminjaman/{peminjaman}', ['as'=> 'peminjaman.show', 'uses' => 'PeminjamanController@show']);
Route::get('peminjaman/{peminjaman}/edit', ['as'=> 'peminjaman.edit', 'uses' => 'PeminjamanController@edit']);

});
